login: &login
  adapter: mysql
  socket: /var/lib/mysql/mysql.sock
  username: root
  password: preventer
  host: localhost
  
development:
  <<: *login
  database: webccq_dev

test:
  <<: *login
  database: webccq_test
  
production:
  <<: *login
  database: webccq

